### PR TITLE
Should be resolved

### PR DESCRIPTION
**Pull request by MidasDoas**
I had changed body.load.js in my repo which hosts the github.io page, and I put it into this repo. So, I believe they should be synced but puzzlingly I didn't need to push anything from my local (this) repo to master, even though I copied over an apparently changed file. Sorry for the debacle, hopefully it works now (it works on midasdoas.github.io)

### CODE REVIEW

**Comment by jonorthwash** [comment]
Could you submit this PR to https://github.com/jonorthwash/ud-annotatrix/ ?

**Comment by MidasDoas** [comment]
It says jonorthwash/ud-annotatrix is synced with MidasDoas/ud-annotatrix. I diff -r'd the directories and .git/index was the only thing different between the two, so I did some research into what it was, moved it, deleted it, tested that my io page still worked, which it did, so I deleted it from jonorthwash/ud-annotatrix and pushed, but it still says the two are synced

**Comment by jonorthwash** [comment]
Yes, but MidasDoas/midasdoas.github.io is the one you added the features to...

**Comment by MidasDoas** [comment]
That's right, so I diff'd it with my ud-annotatrix to find out exactly what I changed, copied those changes over, and tried to send a pull request to your ud-annotatrix. Am I confused about something?

**Comment by jonorthwash** [comment]
I don't see a pull request at https://github.com/jonorthwash/ud-annotatrix/pulls ... Perhaps it's me who's confused about something?

**Comment by jonorthwash** [comment]
Oh, okay, I think I see what's going on.  You added the changes from MidasDoas/midasdoas.github.io into the other repos (with the now closed PRs), but din't get the changes from the other repos into MidasDoas/midasdoas.github.io first.  So the fact that https://midasdoas.github.io/visualise.html works doesn't mean anything else will.  The changes from the other repos need to be merged into MidasDoas/midasdoas.github.io—probably with a minor fix or two to make things work—and *then* a PR can be made to jonorthwash/ud-annotatrix.

**Comment by MidasDoas** [comment]
As far as I understand, these changes from the other repos must have been made between my original PR (of 5 of the issues) and my second PR (involving URL decoding), and I didn't think to merge them to my repo before fixing URL decoding. It seems easier, then, to just forego any further PR's, roll back your repo(s) to whatever they were like just before I submitted my second PR, and then add the decoding URL code to body.load.js. That way, you keep the changes I don't have, and get to apply the decoding, which as I remember wasn't hard at all. Tell me what you think.

**Comment by jonorthwash** [comment]
I think it's easier to apply the couple [small] new changes (ed4045b56009a66521f6af2fea83995acf2b43a0, 346cfef0bb60b7922548298d45df1ca7ff5dd5d9—the rest are just to the README.md file) to your repo than to roll anything back.

**Comment by MidasDoas** [comment]
This was a bit confusing because ed4045b and 346cfef had changes in the script portion of visualise.html, which I took out and put into lib/ext/body.load.js a long time ago, so I wasn't sure how that had happened, but I took those changes and just put them into body.load.js. See my new PR

**Comment by jonorthwash** [comment]
That happened that way because the PR hadn't been merged yet.

**Comment by jonorthwash** [comment]
Hm, I merged the PR, pulled it, and committed to jonorthwash.github.io and it doesn't seem to work.  My local repo is also saying it can't pull from midasdoas.github.io: "refusing to merge unrelated histories" (though everything is in synch with MidasDoas/ud-annotatrix).

Could you diff either of my repos or MidasDoas/ud-annotatrix with midasdoas.github.io and see if there are any differences?

**Comment by MidasDoas** [comment]
I diff'd MidasDoas/MidasDoas.github.io and MidasDoas/ud-annotatrix and the only difference was in .git/index which I think is just a file containing data about what files git is keeping track of. Deleting this results in having to git add everything again, which generates a new .git/index; that's why I think this

**Comment by jonorthwash** [comment]
Okay, yes, those are in sync now.  But they are also out of sync with this repo.  Could you submit a PR to jonorthwash/ud-annotatrix now?

**Comment by jonorthwash** [comment]
Actually, they aren't in sync.  Compare these files:
https://github.com/MidasDoas/ud-annotatrix/blob/master/visualise.html
https://github.com/MidasDoas/midasdoas.github.io/blob/master/visualise.html

Also, these:
https://github.com/MidasDoas/ud-annotatrix/blob/master/lib/ext/body.load.js
https://github.com/MidasDoas/MidasDoas.github.io/blob/master/lib/ext/body.load.js

**Comment by jonorthwash** [comment]
@maryszmary, see this conversation

**Comment by MidasDoas** [comment]
That is very odd, because all of my local files are the same (the things that Github thinks are missing from the ud-annotatrix files are there locally, yet git status also reports that it's completely up to date). In any case, the only things missing from ud-annotatrix/lib/ext/body.load.js are comments, and the only thing missing from ud-annotatrix/visualise.html is the line:
    <script type="text/javascript" src="./lib/ext/body.load.js"></script>
which ought to come right before the </body> tag

**Comment by maryszmary** [comment]
Hello everyone! (and sorry for the long time being silent)
I think I've figured out what kept jonorthwash/ud-annotatrix from working.
1) The lack of the string <script type="text/javascript" src="./lib/ext/body.load.js"></script> in jonorthwash/ud-annotatrix/visualise.html was keeping it from working at all. It _is_ important. I put it back.
2) These lines: 
document.location.protocol + '//spyysalo.github.io/annodoc/lib/local/annodoc.js',
document.location.protocol + '//spyysalo.github.io/conllu.js/conllu.js',
were keeping it from work locally (from computer), because in this case document.location.protocol were returning "file:", which is definitely not where you can find the external libraries.

I changed these 2 things, and it works on my computer.

**Comment by maryszmary** [comment]
I've cloned MidasDoas/ud-annotatrix and diff -r'd it with  jonorthwash/ud-annotatrix. Apart from the git files and the two lines that I have changed, I don't see any differences between the two repositories.

**Comment by MidasDoas** [comment]
I would recommend keeping the document.location.protocol in those lines because not having it causes the annotatrix to break over https, which was an issue before. I would suggest just testing it on maryszmary.github.io instead of locally. (Aside: it takes github a few minutes to update the io pages so if you make a change and it doesn't immediately work that's why)

**Comment by maryszmary** [comment]
Hi, @MidasDoas !
Yes, I realize, for which purpose you put document.location.protocol here and I didn't remove it. Instead, I did the following:

var protocol = (document.location.protocol !== 'file:') ? document.location.protocol : 'http:';
...
    protocol + '//spyysalo.github.io/annodoc/lib/local/annodoc.js',
    protocol + '//spyysalo.github.io/conllu.js/conllu.js',

In this way, you can both avoid the https problem and let it work locally.

And yes, I'm already testing it at maryszmary.github.io: https://maryszmary.github.io/ud-annotatrix/visualise.html :)

**Comment by MidasDoas** [comment]
Ah - nice. Just got worried for a second ;)

**Comment by jonorthwash** [comment]
This sounds great.  I was also little worried, @maryszmary , about how you handled that, but it sounds like you did it the right way.  Cool.

Now, @maryszmary , we should go through the issues that @MidasDoas's PR was meant to address and decide whether each one can be closed, or if further work is needed.  Could you assess each one and leave a comment with the status of it?  There are also some [comments](https://wikis.swarthmore.edu/ling073/User:Twarner2/Final_project#What_I_Did) that I've made on his work already that might need to be added to the issues.

**Pull request merged**
